// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

// Task defined in Rust that Swift executes
typedef void (*UniFfiRustTaskCallback)(const void * _Nullable);

// Callback to execute Rust tasks using a Swift Task
//
// Args:
//   executor: ForeignExecutor lowered into a size_t value
//   delay: Delay in MS
//   task: UniFfiRustTaskCallback to call
//   task_data: data to pass the task callback
typedef void (*UniFfiForeignExecutorCallback)(size_t, uint32_t, UniFfiRustTaskCallback _Nullable, const void * _Nullable);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Callbacks for UniFFI Futures
typedef void (*UniFfiFutureCallbackUInt8)(const void * _Nonnull, uint8_t, RustCallStatus);
typedef void (*UniFfiFutureCallbackInt8)(const void * _Nonnull, int8_t, RustCallStatus);
typedef void (*UniFfiFutureCallbackUnsafeMutableRawPointer)(const void * _Nonnull, void*_Nonnull, RustCallStatus);
typedef void (*UniFfiFutureCallbackUnsafeMutableRawPointer)(const void * _Nonnull, void*_Nonnull, RustCallStatus);
typedef void (*UniFfiFutureCallbackUnsafeMutableRawPointer)(const void * _Nonnull, void*_Nonnull, RustCallStatus);
typedef void (*UniFfiFutureCallbackUnsafeMutableRawPointer)(const void * _Nonnull, void*_Nonnull, RustCallStatus);
typedef void (*UniFfiFutureCallbackUnsafeMutableRawPointer)(const void * _Nonnull, void*_Nonnull, RustCallStatus);
typedef void (*UniFfiFutureCallbackRustBuffer)(const void * _Nonnull, RustBuffer, RustCallStatus);

// Scaffolding functions
void uniffi_proton_pass_common_mobile_fn_free_aliasprefixvalidator(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_pass_common_mobile_fn_constructor_aliasprefixvalidator_new(RustCallStatus *_Nonnull out_status
    
);
void uniffi_proton_pass_common_mobile_fn_method_aliasprefixvalidator_validate(void*_Nonnull ptr, RustBuffer prefix, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_pass_common_mobile_fn_free_loginvalidator(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_pass_common_mobile_fn_constructor_loginvalidator_new(RustCallStatus *_Nonnull out_status
    
);
void uniffi_proton_pass_common_mobile_fn_method_loginvalidator_validate(void*_Nonnull ptr, RustBuffer login, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_pass_common_mobile_fn_free_emailvalidator(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_pass_common_mobile_fn_constructor_emailvalidator_new(RustCallStatus *_Nonnull out_status
    
);
int8_t uniffi_proton_pass_common_mobile_fn_method_emailvalidator_is_email_valid(void*_Nonnull ptr, RustBuffer email, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_pass_common_mobile_fn_free_totpurisanitizer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_pass_common_mobile_fn_constructor_totpurisanitizer_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_proton_pass_common_mobile_fn_method_totpurisanitizer_uri_for_editing(void*_Nonnull ptr, RustBuffer original_uri, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_pass_common_mobile_fn_method_totpurisanitizer_uri_for_saving(void*_Nonnull ptr, RustBuffer original_uri, RustBuffer edited_uri, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_pass_common_mobile_fn_free_totpuriparser(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_pass_common_mobile_fn_constructor_totpuriparser_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_proton_pass_common_mobile_fn_method_totpuriparser_parse(void*_Nonnull ptr, RustBuffer uri_string, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_pass_common_mobile_fn_func_library_version(RustCallStatus *_Nonnull out_status
    
);
RustBuffer ffi_proton_pass_common_mobile_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_proton_pass_common_mobile_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_proton_pass_common_mobile_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_proton_pass_common_mobile_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_proton_pass_common_mobile_checksum_func_library_version(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_aliasprefixvalidator_validate(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_loginvalidator_validate(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_emailvalidator_is_email_valid(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_totpurisanitizer_uri_for_editing(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_totpurisanitizer_uri_for_saving(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_method_totpuriparser_parse(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_constructor_aliasprefixvalidator_new(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_constructor_loginvalidator_new(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_constructor_emailvalidator_new(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_constructor_totpurisanitizer_new(void
    
);
uint16_t uniffi_proton_pass_common_mobile_checksum_constructor_totpuriparser_new(void
    
);
uint32_t ffi_proton_pass_common_mobile_uniffi_contract_version(void
    
);

