repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
        pass_filenames: true
        
      - id: swiftlint-local
        name: SwiftLint
        entry: swiftlint lint --quiet --strict --config .swiftlint.yml
        language: system
        types: [swift]
        pass_filenames: false

exclude: ^\.build/
